spring.application.name=catalog-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/streamhub
spring.datasource.username=denny
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true