###
#GET http://localhost:8081/movies/{{id}}
GET http://localhost:8081/movies/12

### Create a new movie
POST http://localhost:8081/movies
Content-Type: application/json

{
  "title": "Inception",
  "description": "A thief enters dreams to steal and plant ideas.",
  "genre": "Sci-Fi",
  "releaseYear": 2010,
  "durationMinutes": 148,
  "thumbnailUrl": "https://example.com/inception.jpg",
  "mediaUrl": "https://example.com/inception.mp4"
}

### Test bad request
POST http://localhost:8081/movies
Content-Type: application/json

{
  "title": "",
  "description": "Bad request test",
  "genre": "",
  "releaseYear": null,
  "durationMinutes": 0
}