spring.application.name=streamhub
spring.datasource.url=jdbc:postgresql://localhost:5432/streamhub?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=denny
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
resilience4j.retry.instances.catalog.max-attempts=3
resilience4j.retry.instances.catalog.wait-duration=300ms
logging.level.io.github.resilience4j.retry=DEBUG
resilience4j.circuitbreaker.instances.catalog.sliding-window-size=5
resilience4j.circuitbreaker.instances.catalog.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.catalog.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.catalog.wait-duration-in-open-state=10s
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
resilience4j.retry.instances.catalog.retry-exceptions[0]=org.springframework.web.client.ResourceAccessException
resilience4j.retry.instances.catalog.ignore-exceptions[0]=io.github.resilience4j.circuitbreaker.CallNotPermittedException